export const CHANGE_HOVER_SUGGESTION = 'CHANGE_HOVER_SUGGESTION';
export const SEARCH_CHANGE_KEYWORD = 'SEARCH_CHANGE_KEYWORD';

export const COUNT_DOWN_HOVER_SUGGESTION = 'COUNT_DOWN_HOVER_SUGGESTION';
export const COUNT_UP_HOVER_SUGGESTION = 'COUNT_UP_HOVER_SUGGESTION';
export const MOUSE_HOVER_SUGGESTION = 'MOUSE_HOVER_SUGGESTION';
