export const CHANGE_HOVER_SUGGESTION = 'CHANGE_HOVER_SUGGESTION';
export const SEARCH_CHANGE_KEYWORD = 'SEARCH_CHANGE_KEYWORD';
export const SEARCH_CHECK_CLICK_OUT_SIDE = 'SEARCH_CHECK_CLICK_OUT_SIDE';
export const COUNT_DOWN_HOVER_SUGGESTION = 'COUNT_DOWN_HOVER_SUGGESTION';
export const COUNT_UP_HOVER_SUGGESTION = 'COUNT_UP_HOVER_SUGGESTION';
export const MOUSE_HOVER_SUGGESTION = 'MOUSE_HOVER_SUGGESTION';
export const SEARCH_TOGGLE_SHOW_POPUP = 'SEARCH_TOGGLE_SHOW_POPUP';
export const SEARCH_SET_DEFAULT_NODE_INPUT = 'SEARCH_SET_DEFAULT_NODE_INPUT';
